=== zacharyschmidt/OPGEEdeploytest/OPGEEv4/opgee/etc/opgee.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' elementFormDefault='qualified'>

  <!-- 1. Attribute Definitions -->

  <xs:element name='AttrDefs'>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref='ClassAttrs' maxOccurs='unbounded'/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name='ClassAttrs'>
    <xs:complexType>
      <xs:choice maxOccurs='unbounded'>
        <xs:element minOccurs='0' ref='Options'/>
        <xs:element minOccurs='0' ref='AttrDef'/>
    </xs:choice>
      <xs:attribute name='name' use='required' type='xs:NCName'/>
    </xs:complexType>
  </xs:element>

  <xs:element name='Options'>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs='unbounded' ref='Option'/>
      </xs:sequence>
      <xs:attribute name='name' use='required' type='xs:string'/>
      <xs:attribute name='default' use='required' type='xs:string'/>
    </xs:complexType>
  </xs:element>

  <xs:element name='Option'>
    <xs:complexType mixed='true'>
      <xs:attribute name='desc' type='xs:string'/>
      <xs:attribute name='label' type='xs:string'/>
    </xs:complexType>
  </xs:element>

  <xs:element name='AttrDef'>
    <xs:complexType mixed='true'>
      <xs:attribute name='desc'/>
      <xs:attribute name='name' use='required' type='xs:string'/>
      <xs:attribute name='options' type='xs:string'/>
      <xs:attribute name='type' type='xs:NCName'/>
      <xs:attribute name='unit'/>
            <xs:attribute name='exclusive'/>      <!-- exclusive binary attributes; only one can be 1 -->
            <xs:attribute name='synchronized'/>   <!-- synchronized attributes; must have the same value -->

      <!-- Numeric constraints -->
      <xs:attribute name="GT" type="xs:decimal"/>
      <xs:attribute name="GE" type="xs:decimal"/>
      <xs:attribute name="LT" type="xs:decimal"/>
      <xs:attribute name="LE" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>

  <!-- end of Attribute Definitions -->

  <!-- 2. Analysis and Field Definitions -->

	<!-- Attribute types -->
	<xs:simpleType name="PhaseType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="gas"/>
			<xs:enumeration value="liquid"/>
			<xs:enumeration value="solid"/>
    </xs:restriction>
	</xs:simpleType>

	<xs:element name='Model'>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element minOccurs='0' ref="AttrDefs"/>
				<xs:element minOccurs='0' ref="A"/>
				<xs:element minOccurs='0' ref="Analysis"/>
        <xs:element minOccurs='0' ref='Field'/>
        <xs:element minOccurs="0" ref='TableUpdate'/>
			</xs:choice>
      <xs:attribute name='schema_version' use='optional' type='xs:string'/> <!-- default is "4.0.0.a" -->
		</xs:complexType>
    </xs:element>

	<xs:element name='Analysis'>
    <xs:complexType>
			<xs:choice maxOccurs='unbounded'>
        <xs:element ref='A'/>
        <xs:element minOccurs='0' ref='Field'/>
        <xs:element minOccurs='0' ref='Group'/>   <!-- field groups to include in this analysis -->
      </xs:choice>
      <xs:attribute name='name' use='required' type='xs:NCName'/>
      <xs:attribute name='delete' type='xs:boolean'/>
    </xs:complexType>
	</xs:element>

	<xs:element name='Group'>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='xs:string'>
			    <xs:attribute name='regex' default='0' type='xs:boolean'/>
          <xs:attribute name='delete' type='xs:boolean'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

	<xs:element name='Field'>
    <xs:complexType>
      <xs:choice maxOccurs='unbounded'>
        <xs:element minOccurs='0' ref='A'/>
        <xs:element minOccurs='0' ref='Group'/>       <!-- groups this field belongs to -->
        <xs:element minOccurs='0' ref='Aggregator'/>
				<xs:element minOccurs='0' ref='Process'/>
  			<xs:element minOccurs='0' ref='ProcessChoice'/>
				<xs:element ref='Stream'/>
      </xs:choice>
			<xs:attribute name='name' use='required' type='xs:string'/>
			<xs:attribute name='enabled' default='1' type='xs:boolean'/>
			<xs:attribute name='extend' default='0' type='xs:boolean'/>
      <xs:attribute name='delete' type='xs:boolean'/>
      <xs:attribute name="modifies" type="xs:string"/>
      <xs:attribute name="modified" type="xs:string"/>    <!-- set after a modified field has been copied to avoid doing so again -->
    </xs:complexType>
  </xs:element>

  <xs:element name="Cell">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='xs:string'>
          <xs:attribute name='row' use='required' type='xs:string'/>
          <xs:attribute name='col' use='required' type='xs:string'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="TableUpdate">
    <xs:complexType>
      <xs:choice maxOccurs='unbounded'>
        <xs:element minOccurs='1' ref='Cell'/>
      </xs:choice>
      <xs:attribute name='name' use='required' type='xs:string'/>
    </xs:complexType>
  </xs:element>

  <xs:element name='A'>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='xs:string'>
          <xs:attribute name='name' use='required' type='xs:NCName'/>
          <xs:attribute name='delete' type='xs:boolean'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
	</xs:element>

	<!-- use type forward reference to define recursive structure -->
	<xs:element name="Aggregator" type="AggregatorType"/>

	<xs:complexType name="AggregatorType">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="Aggregator" type="AggregatorType"/>
			<xs:element minOccurs='0' ref='A'/>
			<xs:element minOccurs='0' ref='Process'/>
			<xs:element minOccurs='0' ref='ProcessChoice'/>
		</xs:choice>
		<xs:attribute name='name' type='xs:string'/>
		<xs:attribute name='enabled' default='1' type='xs:boolean'/>
    <xs:attribute name='delete' type='xs:boolean'/>
	</xs:complexType>

  <!-- identifier for stream contents -->
  <xs:element name='Contains'>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='xs:string'>
          <xs:attribute name='delete' type='xs:boolean'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name='Stream'>
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="2" maxOccurs="2" ref='A'/>
        <xs:element ref='Component'/>
        <xs:element ref="Contains"/>
      </xs:choice>
      <xs:attribute name='name'/>                      <!-- computed if not provided -->
      <xs:attribute name='src' use='required'/>
      <xs:attribute name='dst' use='required'/>
      <xs:attribute name="impute" default="1"/>        <!-- if false, don't traverse during impute() processing -->
      <xs:attribute name="boundary" type='xs:string'/>
      <xs:attribute name='delete' type='xs:boolean'/>
    </xs:complexType>
  </xs:element>

  <xs:element name='Component'>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='xs:decimal'>
          <xs:attribute name='name' use='required'/>
          <xs:attribute name='phase' use='required' type="PhaseType"/>
          <xs:attribute name='delete' type='xs:boolean'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

	<xs:element name='Process'>
    <xs:complexType>
			<xs:choice maxOccurs="unbounded">
        <xs:element minOccurs='0' ref='A'/>
      </xs:choice>
      <xs:attribute name='class' use='required'/>
      <xs:attribute name='name' type='xs:NCName'/>
      <xs:attribute name='desc' type='xs:string'/>
      <xs:attribute name='enabled' default='1' type='xs:boolean'/>
      <xs:attribute name='extend' default='0' type='xs:boolean'/>
      <xs:attribute name='impute-start' default='0' type='xs:boolean'/>
      <xs:attribute name='cycle-start' default='0' type='xs:boolean'/>
      <xs:attribute name="boundary" type='xs:string'/>
      <xs:attribute name='delete' type='xs:boolean'/>
      <xs:attribute name='after' type='xs:boolean'/>  <!-- run this process after "normal" processing completes -->
    </xs:complexType>
	</xs:element>

	<!-- use type forward reference to define recursive structure -->
	<xs:element name="ProcessChoice" type="ProcessChoiceType"/>

	<xs:complexType name="ProcessChoiceType">
		<xs:choice maxOccurs="unbounded">
 				<xs:element minOccurs='1' ref='ProcessGroup'/>
		</xs:choice>
    <xs:attribute name='name' use='required' type='xs:string'/>
    <xs:attribute name='extend' default='0' type='xs:boolean'/>
    <xs:attribute name='default' type='xs:string'/>
    <xs:attribute name='delete' type='xs:boolean'/>
	</xs:complexType>

	<xs:element name='ProcessGroup'>
    <xs:complexType>
      <xs:choice maxOccurs='unbounded'>
 				<xs:element minOccurs='1' ref='ProcessRef'/>
				<xs:element minOccurs='0' ref='StreamRef'/>
 				<xs:element minOccurs='1' ref='ProcessChoice'/>
      </xs:choice>
			<xs:attribute name='name' use='required' type='xs:string'/>
      <xs:attribute name='delete' type='xs:boolean'/>
    </xs:complexType>
  </xs:element>

	<xs:element name='ProcessRef'>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='xs:string'>
          <xs:attribute name='name' use='required' type='xs:string'/>
          <xs:attribute name='delete' type='xs:boolean'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name='StreamRef'>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='xs:string'>
          <xs:attribute name='name' use='required' type='xs:string'/>
          <xs:attribute name='delete' type='xs:boolean'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== zacharyschmidt/OPGEEdeploytest/OPGEEv4/tests/files/test_attr_constraints_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../opgee/etc/opgee.xsd">

	<Analysis name="test">
		<Field name="test"/>
	</Analysis>

	<Field name="test">
		<Group>First test</Group>		<!-- to test regex group matching -->
		<A name="country">USA</A>

		<!-- these are mutually exclusive -->
		<A name="steam_flooding">0</A>
		<A name="gas_flooding">1</A>

		<!-- these are synchronized -->
		<A name="sync_attr_1">1</A>
		<A name="sync_attr_2">1</A>

		<!-- fails constraint LT="250" -->
		<A name="age">300</A>

		<Process class="ProcA" desc="Test process 1"/>
		<Process class="ProcB" desc="Test process 2"/>

		<Stream src="ProcA" dst="ProcB">
			<A name="temperature">90.0</A>
			<A name="pressure">150.0</A>
			<Component name="oil" phase="liquid">100</Component>
			<Contains>crude oil</Contains>
		</Stream>
	</Field>

</Model>

=== zacharyschmidt/OPGEEdeploytest/OPGEEv4/tests/files/test_merge_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../opgee/etc/opgee.xsd">

	<Analysis name="other">
		<Field name="other"/>
	</Analysis>

	<Field name="other">
		<A name="country">USA</A>

		<Process class="ProcA" desc="Test process 1"/>
		<Process class="ProcB" desc="Test process 2"/>

		<Stream src="ProcA" dst="ProcB">
			<A name="temperature">90.0</A>
			<A name="pressure">150.0</A>
			<Component name="oil" phase="liquid">100</Component>
			<Contains>crude oil</Contains>
		</Stream>
	</Field>

</Model>

=== zacharyschmidt/OPGEEdeploytest/OPGEEv4/tests/files/test_merge_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../opgee/etc/opgee.xsd">

	<Field name="other">

		<Process class="ProcA" desc="Test process 1">
			<A name="temperature">100.0</A>
			<A name="pressure">185.0</A>
    </Process>

		<!-- Delete first, so both the Contains elements get added -->
		<Stream src="ProcA" dst="ProcB" delete="1"/>

		<Stream src="ProcA" dst="ProcB">
			<A name="temperature">99.0</A>
			<A name="pressure">150.0</A>
			<Component name="oil" phase="liquid">111</Component>

			<!--
			Without the prior delete above, each Contains matches, so content
			is copied over, resulting in just the final Contains node.
			-->
			<Contains>crude oil</Contains>
			<Contains>random substance</Contains>
		</Stream>
	</Field>

</Model>

=== zacharyschmidt/OPGEEdeploytest/OPGEEv4/tests/files/test_model2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../opgee/etc/opgee.xsd">

	<Analysis name="Analysis1">
	  <A name="functional_unit">oil</A>
	  <A name="GWP_horizon">100</A>
	  <A name="GWP_version">AR5</A>
          <Field name="Field1"/>
	</Analysis>

	<Field name="Field1">
		<A name="country">USA</A>
		<A name="offshore">0</A>
		<A name="age">86</A>
		<A name="depth">4936</A>
		<A name="oil_prod">101295</A>
		<A name="num_prod_wells">41539</A>
		<A name="num_water_inj_wells">34426</A>
		<A name="well_diam">3.01</A>
		<A name="prod_index">37.53</A>
		<A name="res_press">1556.6</A>
		<A name="res_temp">200.0</A>
		<A name="GOR">2429.30</A>
		<A name="gas_comp_N2">0.4</A>
		<A name="gas_comp_CO2">0.0</A>
		<A name="gas_comp_C1">96.6</A>
		<A name="gas_comp_C2">2.0</A>
		<A name="gas_comp_C3">1.0</A>
		<A name="gas_comp_C4">0.0</A>
		<A name="gas_comp_H2S">0.0</A>
		<A name="API">32.8</A>

		<Process class="UserProcess1" desc="Test process 1"/>
		<Process class="Boundary" boundary="Production" desc="Test process 2"/>

		<Stream src="UserProcess1" dst="ProductionBoundary">
			<A name="temperature">90.0</A>
			<A name="pressure">150.0</A>
			<Component name="oil" phase="liquid">100</Component>
			<Contains>crude oil</Contains>
		</Stream>

	</Field>
</Model>
